comment_width = 120
condense_wildcard_suffixes = true
edition = "2018"
enum_discrim_align_threshold = 20
# error_on_line_overflow = true
# error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
# width_heuristics = "Max"
wrap_comments = true
